### PR TITLE
Fix Minecraft Java query not being able to specify a hostname

### LINKED ISSUE #77: Issue with minecraft query
While working on integration tests I noticed that Minecraft query doesn't work for popular servers such as `mc.hypixel.net`.

```
$ cargo run --example generic mc mc.hypixel.net
Querying 209.222.114.62 with game Game {
    name: "Minecraft",
    default_port: 25565,
    protocol: Minecraft(
        None,
    ),
}.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AutoQuery', examples/generic.rs:39:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at the output of node-gamedig it succeeds with the "vanilla" protocol which is the equivalent of our java.

Using mc-java there is a packet underflow:

```
$ cargo run --example generic mc-java mc.hypixel.net
Querying 209.222.114.62 with game Game {
    name: "Minecraft (java)",
    default_port: 25565,
    protocol: Minecraft(
        Some(
            Java,
        ),
    ),
}.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PacketUnderflow', examples/generic.rs:39:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by CosminPerRam**
Closes #77

### CODE REVIEW

**Comment by Douile** [comment]
Nice work! 🎉

File: src/protocols/minecraft/types.rs [hunk 1]
```diff
@@ -156,6 +156,20 @@ impl JavaResponse {
     }
 }
 
+pub struct RequestSettings {
+    pub hostname: String,
+    pub protocol_version: i32,
```
Comment (Douile) [inline src/protocols/minecraft/types.rs:161]: It might be worth adding a doc comment about -1 meaning any version, like you mention in the mc example

File: src/socket.rs [hunk 2]
```diff
@@ -20,16 +20,20 @@ pub trait Socket {
...
     socket: net::TcpStream,
+    address: SocketAddr,
 }
 
 impl Socket for TcpSocket {
     fn new(address: &SocketAddr) -> GDResult<Self> {
         Ok(Self {
             socket: net::TcpStream::connect(address).map_err(|e| SocketConnect.context(e))?,
+            address: *address,
         })
```
Comment (Douile) [inline src/socket.rs:37]: Would it be better to use `self.socket.peer_addr()` instead of implicitly copying the address? Maybe not as that is wrapped in a result.

File: src/protocols/minecraft/types.rs [hunk 3]
```diff
@@ -238,3 +252,10 @@ pub(crate) fn get_string<B: ByteOrder>(buffer: &mut Buffer<B>) -> GDResult<Strin
 
     String::from_utf8(text).map_err(|e| PacketBad.context(e))
 }
+
+pub(crate) fn as_string(value: &str) -> Vec<u8> {
+    let mut buf = as_varint(value.len() as i32);
```
Comment (Douile) [inline src/protocols/minecraft/types.rs:257]: I'm nitpicking but this would surely wrap to negative if greater than `i32::MAX` (very unlikely), we could use `try_into()` to catch that instead of sending a potentially malformed packet in that case (I could be misunderstanding `as_varint`). Altough to be honest i'm sure the same conversion is done elsewhere.

**Review by Douile — COMMENTED** [review]
Sorry I can't code while on holiday so I decided to review this PR. Thanks for getting this fixed.

File: src/protocols/minecraft/types.rs (hunk 3 above)
Comment (CosminPerRam) [reply src/protocols/minecraft/types.rs:257]: I wouldn't ever think that we'll have a String passed here greater than `2_147_483_647`, but this could be added for safety.

File: src/socket.rs (hunk 2 above)
Comment (CosminPerRam) [reply src/socket.rs:37]: I don't think so, we already have the address and I guess (?) that internally `peer_addr` also does a copy.

**Comment by CosminPerRam** [comment]
> Sorry I can't code while on holiday so I decided to review this PR.

Thanks for putting the time for it (I always appreciate it), although holidays are for taking a break for this usual stuff (;

File: src/socket.rs (hunk 2 above)
Comment (Douile) [reply src/socket.rs:37]: Yeah it most likely does.

**Review by Douile — APPROVED** [review]
Looks good to me 🚀!
