### PR TITLE
Change the app id for "The Forest" so it doesn't fail

### LINKED ISSUE #231: The Forest not working but works in node version
**Describe the bug**
The forest returns an error but the node version of gamedig works.

**Steps To Reproduce**
```bash
# install rust version of gamedig cli
cargo install gamedig-cli --git https://github.com/gamedig/rust-gamedig.git --locked
# install node version of gamedig cli
npm install gamedig -g

gamedig-cli query -g theforest --ip 173.240.158.46 -p 26907 -f json
gamedig --type theforest 173.240.158.46:26907
```

**Expected behavior**
both commands return similar results

**Actual behavior**
gamedig-cli (the rust version) returns an error
You get a similar error when using the library, the cli was just easier to demonstrate.

**Screenshots or Data**
image

**Additional context**
You can find servers to test this with here: https://gamemonitoring.net/the-forest/servers (clicking into them shows the query port)

### PR DESCRIPTION
**Pull request by paul-hansen**
Fixes #231

Changes it to use the app id of the game instead of the dedicated server. Idk if this is proper or not but it makes it work.

### CODE REVIEW

**Comment by cainthebest** [comment]
Hello, ty for the PR! I will review this tonight.

File: crates/lib/src/games/definitions.rs [hunk 1]
```diff
@@ -124,7 +124,7 @@ pub static GAMES: Map<&'static str, Game> = phf_map! {
     "soulmask" => game!("Soulmask", 27015, Protocol::Valve(Engine::new(2_646_460))),
     "serioussam" => game!("Serious Sam", 25601, Protocol::Gamespy(GameSpyVersion::One)),
     "squad" => game!("Squad", 27165, Protocol::Valve(Engine::new(393_380))),
-    "theforest" => game!("The Forest", 27016, Protocol::Valve(Engine::new(556_450))),
+    "theforest" => game!("The Forest", 27016, Protocol::Valve(Engine::new(242_760))),
```
Comment (cainthebest) [inline crates/lib/src/games/definitions.rs:127]: We can include both ids here so that we support both types of host

```
"theforest" => game!("The Forest", 27016, Protocol::Valve(Engine::new_with_dedicated(242_760, 556_450))),
```

This should fix the issue

**Review by cainthebest — CHANGES_REQUESTED** [review]

File: crates/lib/src/games/definitions.rs (hunk 1 above)
Comment (paul-hansen) [reply crates/lib/src/games/definitions.rs:127]: Oh, nice! I wondered if there was a better way, should have poked around a bit more. Will get that added now, thanks!

**Review by cainthebest — APPROVED** [review]
LGTM 🚀
